compphp:
    image: compare-php
    volumes:
        - ./:/var/www/app
    ports:
        - "89:80"
    links:
        - compelasticsearch

compelasticsearch:
    image: compare-elasticsearch
    expose:
        - "9200"
